Properties:
  GlobalCooldown: 500
  SeaLevel: 62
  Chat:
    ChatPrefixes: true
    AirPrefix: "[&7Air&f]"
    WaterPrefix: "[&bWater&f]"
    EarthPrefix: "[&aEarth&f]"
    FirePrefix: "[&cFire&f]"
    AvatarPrefix: "[&5Avatar&f]"
    ChiPrefix: "[&6Chi]"
  Air:
    CanBendWithWeapons: false
  Water:
    CanBendWithWeapons: false
    NightFactor: 1.5
  Earth:
    CanBendWithWeapons: true
    EarthbendableBlocks:
    - STONE
    - COAL_ORE
    - DIAMOND_ORE
    - DIRT
    - GOLD_ORE
    - GRASS
    - GRAVEL
    - IRON_ORE
    - LAPIS_ORE
    - NETHERRACK
    - REDSTONE_ORE
    - SAND
    - SANDSTONE
  Fire:
    CanBendWithWeapons: true
    DayFactor: 1.5
  Chi:
    CanBendWithWeapons: false
Abilities:
  AvatarState:
    Enabled: true
    Description: "The signature ability of the Avatar, this is a toggle. Click to activate to become nearly unstoppable. While in the Avatar State, the user takes severely reduced damage from all sources, regenreates health rapidly, and is granted extreme speed. Nearly all abilities are incredibly amplified in this state. Additionally, AirShield and FireJet become toggle-able abilities and last until you deactivate them or the Avatar State. Click again with the Avatar State selected to deactivate it."
  Air:
    Passive:
      Factor: 0.3
      Speed: 2
      Jump: 3
    AirBlast:
      Enabled: true
      Description: "AirBlast is the most fundamental bending technique of an airbender. To use, simply left-click in a direction. A gust of wind will be created at your fingertips, launching anything in its path harmlessly back. A gust of air can extinguish fires on the ground or on a player, can cool lava, and can flip levers and activate buttons. Additionally, tapping sneak will change the original of your next AirBlast to your targeted location."
      Speed: 25
      Range: 20
      Radius: 2
      Push: 3.5
    AirBubble:
      Enabled: true
      Description: "To use, the bender must merely have the ability selected. All water around the user in a small bubble will vanish, replacing itself once the user either gets too far away or selects a different ability."
      Radius: 7
    AirBurst:
      Enabled: true
      Description: "AirBurst is one of the most powerful abilities in an airbender's arsenal. To use, press and hold sneak to charge your burst. Once charged, you can either release sneak to launch a cone-shaped burst of air in front of you, or click to release theb urst in a sphere around you. Additionally, having this ability selected when you land on the ground from a large enough fall will create a burst of air around you."
    AirScooter:
      Enabled: true
      Description: "AirScooter is a fast means of transportation. To use, sprint, jump then click with this ability selected. YOu will hop on a scooter of air and be propelled forward in the direction you're looking (you don't need to press anything). This ability can be used to levitate above liquids, but it cannot go up steep slopes. Any other actions will deactivate this ability."
      Speed: 0.675
    AirSpout:
      Enabled: true
      Description: "This ability gives the airbender limited sustained levitation. It is a toggle - click to activate and form a whirling spout of air beneath you, lifting you up. You can bend other abilities while using AirSpout. Click again to deactivate this ability."
      Height: 20
    Tornado: 
      Enabled: true
      Description: "To use, simply sneak (default: shift). This will create a swirling vortex at the targeted location. Any creature or object caught in the vortex will be launched up and out in some random direction. If another player gets caught in the vortex, the launching effect is minimal. Tornado can also be used to transport the user. If the user gets caught in his/her own tornado, his/her movements are much more manageable. Provided the user doesn't fall out of the vortex, it will take him to a maximum height and move him in the general direction he/she is looking. Skilled airbenders can scale anything with this ability."
      Radius: 10
      Height: 25
      Range: 25
      MobPushFactor: 1
      PlayerPushFactor: 1
  Water:
    Passive:
      SwimSpeedFactor: 0.7
    Bloodbending:
      Enabled: true
      Description: "This ability was made illegal for a reason. With this ability selected, sneak while targeting something and you will bloodbend that target. Bloodbent targets cannot move, bend, or attack. You are free to control their actions by looking elsewhere - they will be forced to move in that direciton. Additionally, clicking while bloodbending will launch that target off in the direction you're looking. People who are capable of bloodbending are immune to technique, and you are immune to theirs.";
      ThrowFactor: 2
      Range: 10
    OctopusForm:
      Enabled: true
      Description: "This ability allows the waterbender to manipulate a large quantity of water into a form resembling that of an octopus. To use, click to select a water source. Then, hold sneak to channel this ability. While channleing, the water will form itself around you and has a chance to block incoming attacks. Additionally, you can click while channeling to attack things near you, dealing damage and knocking the target back. Releasing shift at any time will dissipate the form."
    PhaseChange:
      Enabled: true
      Description: "To use, simply left-click. Any water you are looking at within range will instantly freeze over into solid ice. Provided you stay within range of the ice and do not unbind FreezeMelt, that ice will not thaw. If, however, you do either of those things the ice will instantly thaw. If you sneak (default: shift), anything around where you are looking at will instantly melt. Since this is a more favorable state for these things, they will never re-freeze unless they would otherwise by nature or some other bending ability. Additionally, if you tap sneak while targeting water with FreezeMelt, it will evaporate water around that block that is above sea level."
      Range: 20
      Radius: 5
    Plantbending:
      RegrowTime: 180000
    WaterBubble:
      Enabled: true
      Description: "To use, the bender must merely have the ability selected. All water around the user in a small bubble will vanish, replacing itself once the user either gets too far away or selects a different ability."
      Radius: 7
    WaterManipulation:
      Enabled: true
      Description: "To use, place your cursor over a waterbendable object and tap sneak (default: shift). Smoke will appear where you've selected, indicating the origin of your ability. After you have selected an origin, simply left-click in any direction and you will see your water spout off in that direction, slicing any creature in its path. If you look towards a creature when you use this ability, it will target that creature. A collision from Water Manipulation both knocks the target back and deals some damage. Alternatively, if you have the source selected and tap shift again, you will be able to control the water more directly."
      Damage: 3.0
      Range: 20
      Speed: 35
      Push: .3
    WaterSpout:
      Enabled: true
      Description: "To use this ability, click while over or in water. You will spout water up from beneath you to experience controlled levitation. This ability is a toggle, so you can activate it then use other abilities and it will remain on. If you try to spout over an area with no water, snow, or ice, the spout will dissipate and you will fall. Click again with this ability selected to deactivate it."
      Height: 20
  Earth:
    Passive:
      Duration: 2500
    Catapult:
      Enabled: true
      Description: "To use, left-click while looking in the direction you want to be launched. A pillar of earth will jut up from under you and launch you in that direction - if and only if there is enough earth behind where you're looking to launch you. Skillful use of this ability takes much time and work, and it does result in the death of certain gung-ho earthbenders. if you plan to use this ability, be sure you've read about your passive ability you innately have as an earthbender."
      Length: 7
      Speed: 12
      Push: 5
    Collapse:
      Enabled: true
      Description: "To use, simply left-click an earthbendable block. That block and the earthbendable blocks above it will be shoved back into the earth below, if they can. This ability does have the capacity to trap something inside of it, although it is incredibly difficult to do so. Additionally, press sneak with this ability to affect an area around your targeted location - all earth that can be moved downwards will be moved downwards. This ability is especially risky or deadly in caves, depending on the earthbender's goal and technique."
      Range: 20
      Radius: 7
      Speed: 8
    RaiseEarth:
      Enabled: true
      Description: "To use, simply left-click on an earthbendable block. A column of earth will shoot upwards from that location. Anything in the way of the column will be brought up with it, leaving talented benders the ability to trap brainless entities up there. Additionally, simply sneak (default shift) looking at an earthbendable block. A wall of earth will shoot upwards from that location. Anything in the way of the wall will be brought up with it."
      Column:
        Height: 6
      Wall:
        Range: 15
        Height: 6
        Width: 6
  Fire:
    FireJet:
      Enabled: true
      Description: "This ability is used for a limited burst of flight for firebenders. Clicking with this ability selected will launch you in the direction you're looking, granting you controlled flight for a short time. This ability can be used mid-air to prevent falling to your death, but on the ground it can only be used if standing on a block that's ignitable (e.g. not snow or water)."
      Speed: 0.7
      Duration: 1500
      Cooldown: 6000
    HeatControl:
      Enabled: true
      Description: "While this ability is selected, the firebender becomes impervious to fire damage and cannot be ignited. If the user left-clicks with this ability, the targeted area will be extinguished, although it will leave any creature burning engulfed in flames. This ability can also cool lava. If this ability is used while targeting ice or snow, it will instead melt blocks in that area. Finally, sneaking with this ability will cook any food in your hand."
      Extinguish:
        Range: 20
        Radius: 7
      Melt:
        Range: 15
        Radius: 5
  Chi:
    Passive:
      FallReductionFactor: 0.5
      Speed: 1
      Jump: 2
      BlockChi:
        Duration: 2500
        DodgeChance: 25
      Paralyze:
        Enabled: true
        Description: "Paralyzes the target, making them unable to do anything for a short period of time. This ability has a long cooldown."
        Cooldown: 15000
        Duration: 2000
Storage:
  engine: sqlite
  MySQL:
    host: localhost
    port: 3306
    pass: ''
    db: minecraft
    user: root