Properties:
  GlobalCooldown: 500
  SeaLevel: 62
  Chat:
    ChatPrefixes: true
    AirPrefix: "[&7Air&f]"
    WaterPrefix: "[&bWater&f]"
    EarthPrefix: "[&aEarth&f]"
    FirePrefix: "[&cFire&f]"
    AvatarPrefix: "[&5Avatar&f]"
    ChiPrefix: "[&6Chi]"
  Air:
    CanBendWithWeapons: false
  Water:
    CanBendWithWeapons: false
    NightFactor: 1.5
  Earth:
    CanBendWithWeapons: true
    EarthbendableBlocks:
    - STONE
    - COAL_ORE
    - DIAMOND_ORE
    - DIRT
    - GOLD_ORE
    - GRASS
    - GRAVEL
    - IRON_ORE
    - LAPIS_ORE
    - NETHERRACK
    - REDSTONE_ORE
    - SAND
    - SANDSTONE
  Fire:
    CanBendWithWeapons: true
    DayFactor: 1.5
  Chi:
    CanBendWithWeapons: false
Abilities:
  AvatarState:
    Enabled: true
    Description: "The signature ability of the Avatar, this is a toggle. Click to activate to become nearly unstoppable. While in the Avatar State, the user takes severely reduced damage from all sources, regenreates health rapidly, and is granted extreme speed. Nearly all abilities are incredibly amplified in this state. Additionally, AirShield and FireJet become toggle-able abilities and last until you deactivate them or the Avatar State. Click again with the Avatar State selected to deactivate it."
  Air:
    Passive:
      Factor: 0.3
      Speed: 2
      Jump: 3
    AirBlast:
      Enabled: true
      Description: "AirBlast is the most fundamental bending technique of an airbender. To use, simply left-click in a direction. A gust of wind will be created at your fingertips, launching anything in its path harmlessly back. A gust of air can extinguish fires on the ground or on a player, can cool lava, and can flip levers and activate buttons. Additionally, tapping sneak will change the original of your next AirBlast to your targeted location."
      Speed: 25
      Range: 20
      Radius: 2
      Push: 3.5
    AirBurst:
      Enabled: true
      Description: "AirBurst is one of the most powerful abilities in an airbender's arsenal. To use, press and hold sneak to charge your burst. Once charged, you can either release sneak to launch a cone-shaped burst of air in front of you, or click to release theb urst in a sphere around you. Additionally, having this ability selected when you land on the ground from a large enough fall will create a burst of air around you."
    AirScooter:
      Enabled: true
      Description: "AirScooter is a fast means of transportation. To use, sprint, jump then click with this ability selected. YOu will hop on a scooter of air and be propelled forward in the direction you're looking (you don't need to press anything). This ability can be used to levitate above liquids, but it cannot go up steep slopes. Any other actions will deactivate this ability."
      Speed: 0.675
    AirSpout:
      Enabled: true
      Description: "This ability gives the airbender limited sustained levitation. It is a toggle - click to activate and form a whirling spout of air beneath you, lifting you up. You can bend other abilities while using AirSpout. Click again to deactivate this ability."
      Height: 20
    Tornado: 
      Enabled: true
      Description: "To use, simply sneak (default: shift). This will create a swirling vortex at the targeted lcoation. Any creature or object caught in the vortex will be launched up and out in some random direction. If another player gets caught in the vortex, the launching effect is minimal. Tornado can also be used to transport the user. If the user gets caught in his/her own tornado, his/her movements are much more manageable. Provided the user doesn't fall out of the vortex, it will take him to a maximum height and move him in the general direction he/she is looking. Skilled airbenders can scale anything with this ability."
      Radius: 10
      Height: 25
      Range: 25
      MobPushFactor: 1
      PlayerPushFactor: 1
  Water:
    Passive:
      SwimSpeedFactor: 0.7
    Bloodbending:
      Enabled: true
      Description: "This ability was made illegal for a reason. With this ability selected, sneak while targeting something and you will bloodbend that target. Bloodbent targets cannot move, bend, or attack. You are free to control their actions by looking elsewhere - they will be forced to move in that direciton. Additionally, clicking while bloodbending will launch that target off in the direction you're looking. People who are capable of bloodbending are immune to technique, and you are immune to theirs.";
      ThrowFactor: 2
      Range: 10
    Plantbending:
      RegrowTime: 180000
    WaterSpout:
      Enabled: true
      Description: "To use this ability, click while over or in water. You will spout water up from beneath you to experience controlled levitation. This ability is a toggle, so you can activate it then use other abilities and it will remain on. If you try to spout over an area with no water, snow, or ice, the spout will dissipate and you will fall. Click again with this ability selected to deactivate it."
      Height: 20
  Earth:
    Passive:
      Duration: 2500
    Catapult:
      Enabled: true
      Description: "To use, left-click while looking in the direction you want to be launched. A pillar of earth will jut up from under you and launch you in that direction - if and only if there is enough earth behind where you're looking to launch you. Skillful use of this ability takes much time and work, and it does result in the death of certain gung-ho earthbenders. if you plan to use this ability, be sure you've read about your passive ability you innately have as an earthbender."
      Length: 7
      Speed: 12
      Push: 5
  Fire:
    FireJet:
      Enabled: true
      Description: "This ability is used for a limited burst of flight for firebenders. Clicking with this ability selected will launch you in the direction you're looking, granting you controlled flight for a short time. This ability can be used mid-air to prevent falling to your death, but on the ground it can only be used if standing on a block that's ignitable (e.g. not snow or water)."
      Speed: 0.7
      Duration: 1500
      Cooldown: 6000
  Chi:
    Passive:
      FallReductionFactor: 0.5
      Speed: 1
      Jump: 2
      BlockChi:
        Duration: 2500
        DodgeChance: 25
      Paralyze:
        Enabled: true
        Description: "Paralyzes the target, making them unable to do anything for a short period of time. This ability has a long cooldown."
        Cooldown: 15000
        Duration: 2000
Storage:
  engine: sqlite
  MySQL:
    host: localhost
    port: 3306
    pass: ''
    db: minecraft
    user: root